### ISSUE TITLE
templates: about CMS

### ISSUE THREAD

**Issue by hjhsalo** [cernopendata/cernopendata-pages#10]
**Goal**

Migrate `/about/CMS` page from Invenio2 to Invenio3 based CERN Open Data instance.

**Old look**

http://opendata.cern.ch/about/cms
http://opendata.cern.ch/about/CMS

**New look**

*(no particular wireframe available; just port the text)*

**Old implementation**

* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/templates/about_cms.html
* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/views.py#L298

```console
$ git grep -A 7 'route.*CMS'
invenio_opendata/base/views.py:@blueprint.route('about/CMS')
invenio_opendata/base/views.py-@register_breadcrumb(blueprint, '.about_cms', 'CMS', \
invenio_opendata/base/views.py-                        dynamic_list_constructor = (lambda :\
invenio_opendata/base/views.py-                        [{"url":".about", "text":"About"},\
invenio_opendata/base/views.py-                        {"url":".about_cms","text":"CMS Open Data"}]) )
invenio_opendata/base/views.py-def about_cms():
invenio_opendata/base/views.py-    try:
invenio_opendata/base/views.py-        return render_template('about_cms.html')


$ find . -name about_cms.html
./invenio_opendata/base/templates/about_cms.html
```

**New implementation**

Use Jinja template. Port the old code and clean the CSS a bit.

**Additional actions**

--

**Comment by ioannistsanaktsidis** [comment]
Closing as already merged.
