### ISSUE TITLE
templates: about ATLAS

### ISSUE THREAD

**Issue by hjhsalo** [cernopendata/cernopendata-pages#11]
**Goal**

Migrate `/about/ATLAS` page from Invenio2 to Invenio3 based CERN Open Data instance.

**Old look**

http://opendata.cern.ch/about/atlas
http://opendata.cern.ch/about/ATLAS

**New look**

*(no particular wireframe available; just port the text)*

**Old implementation**

* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/templates/about_atlas.html
* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/views.py#L322

```console
$ git grep -A 7 'route.*ATLAS'
invenio_opendata/base/views.py:@blueprint.route('about/ATLAS')
invenio_opendata/base/views.py-@register_breadcrumb(blueprint, '.about_atlas', 'ATLAS', \
invenio_opendata/base/views.py-                        dynamic_list_constructor = (lambda :\
invenio_opendata/base/views.py-                        [{"url":".about", "text":"About"},\
invenio_opendata/base/views.py-                        {"url":".about_atlas","text":"ATLAS Open Data"}]) )
invenio_opendata/base/views.py-def about_atlas():
invenio_opendata/base/views.py-    try:
invenio_opendata/base/views.py-        return render_template('about_atlas.html')


$ find . -name about_atlas.html
./invenio_opendata/base/templates/about_atlas.html
```

**New implementation**

Use Jinja template. Port the old code and clean the CSS a bit.

**Additional actions**

--

**Comment by annatrz** [comment]
Closing as already addressed.
