### ISSUE TITLE
templates: about LHCb

### ISSUE THREAD

**Issue by hjhsalo** [cernopendata/cernopendata-pages#12]
**Goal**

Migrate `/about/LHCb` page from Invenio2 to Invenio3 based CERN Open Data instance.
Route `/about/lhcb` points to the same template.

**Old look**

http://opendata.cern.ch/about/lhcb
http://opendata.cern.ch/about/LHCb

**New look**

*(no particular wireframe available; just port the text)*

**Old implementation**

* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/templates/about_lhcb.html
* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/views.py#L334

```console
$ git grep -A 7 'route.*LHCb'
invenio_opendata/base/views.py:@blueprint.route('about/LHCb')
invenio_opendata/base/views.py-@register_breadcrumb(blueprint, '.about_lhcb', 'LHCb', \
invenio_opendata/base/views.py-                        dynamic_list_constructor = (lambda :\
invenio_opendata/base/views.py-                        [{"url":".about", "text":"About"},\
invenio_opendata/base/views.py-                        {"url":".about_lhcb","text":"LHCb Open Data"}]) )
invenio_opendata/base/views.py-def about_lhcb():
invenio_opendata/base/views.py-    try:
invenio_opendata/base/views.py-        return render_template('about_lhcb.html')


$ find . -name about_lhcb.html
./invenio_opendata/base/templates/about_lhcb.html
```

**New implementation**

Use Jinja template. Port the old code and clean the CSS a bit.

**Additional actions**

--

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented.
