### ISSUE TITLE
templates: CMS Physics Objects

### ISSUE THREAD

**Issue by hjhsalo** [cernopendata/cernopendata-pages#13]
**Goal**

Migrate `/about/CMS Physics Objects` page from Invenio2 to Invenio3 based CERN Open Data instance.

**Old look**

http://opendata.cern.ch/about/CMS-Physics-Objects/

**New look**

*(no particular wireframe available; just port the text)*

**Old implementation**

* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/templates/about_physics_objects_overview.html
* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/views.py#L358

```console
$ git grep -A 13 'route.*CMS-Physics-Objects'
invenio_opendata/base/views.py:@blueprint.route('about/CMS-Physics-Objects', defaults={'year': None})
invenio_opendata/base/views.py:@blueprint.route('about/CMS-Physics-Objects/<string:year>')
invenio_opendata/base/views.py-@register_breadcrumb(blueprint, '.about_physics', 'CMSS', \
invenio_opendata/base/views.py-                        dynamic_list_constructor = (lambda :\
invenio_opendata/base/views.py-                        [{"url":".about", "text":"About"},\
invenio_opendata/base/views.py-                        {"url":".about_cms", "text":"CMS"},\
invenio_opendata/base/views.py-                        {"url":".about_physics","text":"Physics Objects"}]) )
invenio_opendata/base/views.py-def about_physics(year):
invenio_opendata/base/views.py-    try:
invenio_opendata/base/views.py-        return render_template('about_physics_objects_overview.html', year = year)
invenio_opendata/base/views.py-    except TemplateNotFound:
invenio_opendata/base/views.py-        return abort(404)


$ find . -name about_physics_objects_overview.html
./invenio_opendata/base/templates/about_physics_objects_overview.html
```

**New implementation**

We could first use a simple Jinja template to get started. Basically port the old code and clean the CSS a bit.
This might be implemented as a set of records in the future, since it contains references to Physics Objects of different years.

**Additional actions**

--

**Comment by tiborsimko** [comment]
Moved to https://github.com/cernopendata/opendata.cern.ch/issues/1370
