### ISSUE TITLE
templates: CMS Pile-up Simulation

### ISSUE THREAD

**Issue by hjhsalo** [cernopendata/cernopendata-pages#14]
**Goal**

Migrate `/about/CMS-Pileup-Simulation` page from Invenio2 to Invenio3 based CERN Open Data instance.

**Old look**

http://opendata.cern.ch/about/CMS-Pileup-Simulation/

**New look**

*(no particular wireframe available; just port the text)*

**Old implementation**

* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/templates/cms_pileup_simulation.html
* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/views.py#L383

```console
$ git grep -A 13 'route.*CMS-Pileup-Simulation'
invenio_opendata/base/views.py:@blueprint.route('about/CMS-Pileup-Simulation')
invenio_opendata/base/views.py-@register_breadcrumb(blueprint, '.cms_pileup_simulation', 'CMS', \
invenio_opendata/base/views.py-                        dynamic_list_constructor = (lambda :\
invenio_opendata/base/views.py-                        [{"url":".about", "text":"About"},\
invenio_opendata/base/views.py-                        {"url":".about_cms", "text":"CMS"},\
invenio_opendata/base/views.py-                        {"url":".cms_pileup_simulation","text":"Pileup Simulation"}]) )
invenio_opendata/base/views.py-def cms_pileup_simulation():
invenio_opendata/base/views.py-    try:
invenio_opendata/base/views.py-        return render_template('cms_pileup_simulation.html')
invenio_opendata/base/views.py-    except TemplateNotFound:
invenio_opendata/base/views.py-        return abort(404)


$ find . -name cms_pileup_simulation.html
./invenio_opendata/base/templates/cms_pileup_simulation.html
```

**New implementation**

- We could first use a simple Jinja template to get started. Basically port the old code and clean the CSS a bit.
- This might be implemented as a generic record in the future; no detailed granularity in schema structure, content simply under content-key possibly as Markdown.
- Consider changing the template name to about_cms_pileup_simulation.html since the route pointing to this template is '/about/CMS-Pileup-Simulation' and other templates under route '/about/*' have been namespaced with prefix 'about_'.

**Additional actions**

--

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented.
