### ISSUE TITLE
templates: CMS Simulated Dataset Names

### ISSUE THREAD

**Issue by hjhsalo** [cernopendata/cernopendata-pages#15]
**Goal**

Migrate `about/CMS-Simulated-Dataset-Names` page from Invenio2 to Invenio3 based CERN Open Data instance.

**Old look**

http://opendata.cern.ch/about/CMS-Simulated-Dataset-Names

**New look**

*(no particular wireframe available; just port the text)*

**Old implementation**

* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/templates/cms_simulated_dataset_names.html
* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/views.py#L371

```console
$ git grep -A 13 'route.*CMS-Simulated-Dataset-Names'
invenio_opendata/base/views.py:@blueprint.route('about/CMS-Simulated-Dataset-Names')
invenio_opendata/base/views.py-@register_breadcrumb(blueprint, '.sim_dataset_names', 'CMS', \
invenio_opendata/base/views.py-                        dynamic_list_constructor = (lambda :\
invenio_opendata/base/views.py-                        [{"url":".about", "text":"About"},\
invenio_opendata/base/views.py-                        {"url":".about_cms", "text":"CMS"},\
invenio_opendata/base/views.py-                        {"url":".sim_dataset_names","text":"Simulated Dataset Names"}]) )
invenio_opendata/base/views.py-def sim_dataset_names():
invenio_opendata/base/views.py-    try:
invenio_opendata/base/views.py-        return render_template('cms_simulated_dataset_names.html')
invenio_opendata/base/views.py-    except TemplateNotFound:
invenio_opendata/base/views.py-        return abort(404)


$ find . -name cms_simulated_dataset_names.html
./invenio_opendata/base/templates/cms_simulated_dataset_names.html
```

**New implementation**

- We could first use a simple Jinja template to get started. Basically port the old code and clean the CSS a bit.
- This might be implemented as a generic record in the future; no detailed granularity in schema structure, content simply under content-key possibly as Markdown.
- Consider changing the template name to 'about_cms_simulated_dataset_names.html' since the route pointing to this template is '/about/CMS-Simulated-Dataset-Names' and other templates under route '/about/*' have been namespaced with prefix 'about_'.

**Additional actions**

--

**Comment by annatrz** [comment]
Closed as already addressed
