### ISSUE TITLE
templates: education (new look)

### ISSUE THREAD

**Issue by hjhsalo** [cernopendata/cernopendata-pages#16]
**Goal**

Migrate /education page from Invenio2 to Invenio3 based CERN Open Data instance.

**Old look**

http://opendata.cern.ch/education

**New look**

Mockup:
https://invenio.mybalsamiq.com/projects/cod/Education%20landing%20page%20%28dynamic%29

**Old implementation**

In old implementation view just scrolls down to correct section on homepage. New UI has a separate education-page.

* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/templates/index_scrollspy.html#L553
* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/views.py#L112

**New implementation**

??

**Additional actions**

--

**Comment by tiborsimko** [comment]
Moved to https://github.com/cernopendata/opendata.cern.ch/issues/1369
