### ISSUE TITLE
templates: terms-of-use

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/cernopendata-pages#3]
**Goal**

Migrate `/terms-of-use` page from Invenio2 to Invenio3 based CERN Open Data instance.

**Old look**

http://opendata.cern.ch/terms-of-use

**New look**

*(no particular wireframe available; just port the text)*

**Old implementation**

```console
$ git grep -A 3 'route.*terms-of-use'
invenio_opendata/base/views.py:@blueprint.route('terms-of-use')
invenio_opendata/base/views.py-def terms():
invenio_opendata/base/views.py-    try:
invenio_opendata/base/views.py-        return render_template('termsofuse.html')
$ find . -name termsofuse.html
./invenio_opendata/base/templates/termsofuse.html
```

**New implementation**

Use Jinja template. Port the old code and clean the CSS a bit.

**Additional actions**

Plug the "Terms of Use" page into the new page footer.

**Comment by ioannistsanaktsidis** [comment]
Closing as implemented.
