### ISSUE TITLE
templates: glossary

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/cernopendata-pages#4]
**Goal**

Migrate `/glossary` page from Invenio2 to Invenio3 based CERN Open Data instance.

**Old look**

http://opendata.cern.ch/glossary

**New look**

![glossary wireframe](https://invenio.mybalsamiq.com/mockups/5827216.png)

**Old implementation**

```console
$ git grep -A10 route.*glossary 
invenio_opendata/base/views.py:@blueprint.route('glossary', methods=['GET', 'POST'])
invenio_opendata/base/views.py-@register_breadcrumb(blueprint, '.glossary', 'Glossary', \
invenio_opendata/base/views.py-                        dynamic_list_constructor = (lambda :\
invenio_opendata/base/views.py-                        [{"url":".educate", "text":"Education"},\
invenio_opendata/base/views.py-                        {"url":".glossary","text":"Glossary"}]) )
invenio_opendata/base/views.py-def glossary():
invenio_opendata/base/views.py-    import json, pkg_resources
invenio_opendata/base/views.py-    filepath = pkg_resources.resource_filename('invenio_opendata.base', 'static/json/glossary.json')
invenio_opendata/base/views.py-    with open(filepath,'r') as f:
invenio_opendata/base/views.py-        glossary = json.load(f)
invenio_opendata/base/views.py-
```

**New implementation**

Can be treated as a regular search page? Or needs special formatting? Let's refine the wireframe look with @daslerr @sefeg. 

**Additional actions**

Recognising of glossary terms in pages, and linking to them, was done using the `js/zglossary` library. We should see what we do now that glossary terms will be records.  E.g. use the same library and massage its data from records? E.g. create new nice linker from pages to records?

**Comment by daslerr** [comment]
I talked with @sefeg, and we don't see a reason why the glossary couldn't just be a regular search page. I'll update the wireframe.

**Comment by daslerr** [comment]
I updated the original comment to point to the latest version of the wireframe, which now shows the glossary as a search page.

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented.
