### ISSUE TITLE
templates: about

### ISSUE THREAD

**Issue by hjhsalo** [cernopendata/cernopendata-pages#6]
**Goal**

Migrate `/about` page from Invenio2 to Invenio3 based CERN Open Data instance.

**Old look**

http://opendata.cern.ch/about

**New look**

*(no particular wireframe available; just port the text)*

**Old implementation**

* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/templates/about.html
* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/views.py#L287

```console
$ git grep -A 3 'route.*about'
invenio_opendata/base/views.py:@blueprint.route('about')
invenio_opendata/base/views.py-@register_breadcrumb(blueprint, '.about', 'About', \
invenio_opendata/base/views.py-              dynamic_list_constructor = (lambda :\
invenio_opendata/base/views.py-              [{"url":".about","text":"About"}]))
invenio_opendata/base/views.py-def about():
invenio_opendata/base/views.py-    try:
invenio_opendata/base/views.py-        return render_template('about.html')
invenio_opendata/base/views.py-    except TemplateNotFound:


$ find . -name about.html
./invenio_opendata/base/templates/about.html
```

**New implementation**

Use Jinja template. Port the old code and clean the CSS a bit.

**Additional actions**

--

**Comment by ioannistsanaktsidis** [comment]
Closing as already done.
