### ISSUE TITLE
templates: about dropdown-menu on homepage

### ISSUE THREAD

**Issue by hjhsalo** [cernopendata/cernopendata-pages#7]
**Goal**
Collaborations -dropdown menu should be added to homepage and links to experiment / collaboration about-pages should be moved under this new menu.

Currently links to info pages (about CMS, about ALICE, etc.) of experiments / collaborations are listed under About-dropdown menu.

In new UI-mockups the links have been moved under a new dropdown menu, Collaborations.

**Old look**
![about_dropdown_menu_on_homepage-20170713](https://user-images.githubusercontent.com/9445833/28178721-bfc36d32-67ff-11e7-8bd3-11327f1be5c0.png)

**New look**

![mockup-home_page_about_dropdown](https://user-images.githubusercontent.com/9445833/28178727-c41fb03e-67ff-11e7-93ca-f4e0b9867f5f.png)

![mockup-home_page_collaborations_dropdown](https://user-images.githubusercontent.com/9445833/28178731-c5a53d70-67ff-11e7-9b4f-fa2eb4be29ee.png)

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented.
