### ISSUE TITLE
templates: about ALICE

### ISSUE THREAD

**Issue by hjhsalo** [cernopendata/cernopendata-pages#8]
**Goal**

Migrate `/about/ALICE` page from Invenio2 to Invenio3 based CERN Open Data instance.

**Old look**

http://opendata.cern.ch/about/alice
http://opendata.cern.ch/about/ALICE

**New look**

*(no particular wireframe available; just port the text)*

**Old implementation**

* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/templates/about_alice.html
* https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/views.py#L310

```console
$ git grep -A 7 'route.*ALICE'
invenio_opendata/base/views.py:@blueprint.route('about/ALICE')
invenio_opendata/base/views.py-@register_breadcrumb(blueprint, '.about_alice', 'ALICE', \
invenio_opendata/base/views.py-                        dynamic_list_constructor = (lambda :\
invenio_opendata/base/views.py-                        [{"url":".about", "text":"About"},\
invenio_opendata/base/views.py-                        {"url":".about_alice","text":"ALICE Open Data"}]) )
invenio_opendata/base/views.py-def about_alice():
invenio_opendata/base/views.py-    try:
invenio_opendata/base/views.py-        return render_template('about_alice.html')


$ find . -name about_alice.html
./invenio_opendata/base/templates/about_alice.html
```

**New implementation**

Use Jinja template. Port the old code and clean the CSS a bit.

**Additional actions**

--

**Comment by ioannistsanaktsidis** [comment]
Closing as already implemented.
