### ISSUE TITLE
templates: issues with footer scaling

### ISSUE THREAD

**Issue by hjhsalo** [cernopendata/cernopendata-pages#9]
**What**
On a large (desktop) screen, pages with less content have problems with Footer taking more space than it should. This problem doesn't show up, for example, on homepage since there is enough content to fill the whole page.

"Before" and  "after" screenshots that hopefully highlight the style changes and the footer problem:

![terms_of_use_footer_problem_1-20170712](https://user-images.githubusercontent.com/9445833/28111215-0dbcaf82-66f5-11e7-9e0c-c57e88351880.png)

![terms_of_use_footer_problem_2-20170712](https://user-images.githubusercontent.com/9445833/28111219-0f9007d2-66f5-11e7-99f7-904da8e88257.png)

**Actions**
I'm not sure if this should be fixed globally in cernopendata-theme or should we use some styling tricks to fix the problem only in templates where this problem arises.

**Comment by ioannistsanaktsidis** [comment]
We should apply something like this https://getbootstrap.com/2.3.2/examples/sticky-footer.html.

**Comment by hjhsalo** [comment]
Superseded by https://github.com/cernopendata/cernopendata/pull/30
